/**
 * Dynamic route for shareable repository analysis links
 * Usage: /vercel/next.js
 */
"use client";

import { useEffect, useState } from "react";
import { useParams } from "next/navigation";
import Link from "next/link";

interface AnalysisResult {
  prompt: string;
  repoName: string;
  repoUrl: string;
}

export default function RepoPage() {
  const params = useParams();
  const [result, setResult] = useState<AnalysisResult | null>(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState("");

  const owner = Array.isArray(params.owner) ? params.owner[0] : params.owner;
  const repo = Array.isArray(params.repo) ? params.repo[0] : params.repo;

  useEffect(() => {
    const analyzeRepo = async () => {
      if (!owner || !repo) {
        setError("Invalid repository parameters");
        setLoading(false);
        return;
      }

      try {
        const response = await fetch("/api/analyze", {
          method: "POST",
          headers: {
            "Content-Type": "application/json",
          },
          body: JSON.stringify({
            repository: `${owner}/${repo}`,
          }),
        });

        if (!response.ok) {
          const errorData = await response.json();
          throw new Error(errorData.error || "Failed to analyze repository");
        }

        const data = await response.json();
        setResult({
          prompt: data.prompt,
          repoName: data.repoName,
          repoUrl: data.repoUrl,
        });
      } catch (err) {
        setError(err instanceof Error ? err.message : "An unexpected error occurred");
      } finally {
        setLoading(false);
      }
    };

    analyzeRepo();
  }, [owner, repo]);

  if (loading) {
    return (
      <div className="min-h-screen bg-gradient-to-br from-slate-900 via-slate-800 to-slate-900 flex items-center justify-center">
        <div className="text-center">
          <div className="animate-spin rounded-full h-12 w-12 border-b-2 border-blue-500 mx-auto mb-4"></div>
          <p className="text-white">Analyzing {owner}/{repo}...</p>
        </div>
      </div>
    );
  }

  if (error) {
    return (
      <div className="min-h-screen bg-gradient-to-br from-slate-900 via-slate-800 to-slate-900">
        <div className="max-w-4xl mx-auto px-4 py-12">
          <div className="bg-slate-800 rounded-lg shadow-2xl p-8 border border-slate-700">
            <h1 className="text-2xl font-bold text-white mb-4">Error</h1>
            <p className="text-red-200 mb-6">{error}</p>
            <Link
              href="/"
              className="inline-block px-6 py-2 bg-blue-600 hover:bg-blue-700 text-white font-semibold rounded-lg transition-colors"
            >
              Go Back Home
            </Link>
          </div>
        </div>
      </div>
    );
  }

  return (
    <div className="min-h-screen bg-gradient-to-br from-slate-900 via-slate-800 to-slate-900">
      <div className="max-w-4xl mx-auto px-4 py-12">
        {/* Header with back button */}
        <div className="mb-8">
          <Link
            href="/"
            className="text-blue-400 hover:text-blue-300 text-sm flex items-center gap-2 mb-6"
          >
            ← Back to Home
          </Link>
        </div>

        {/* Results */}
        {result && (
          <div className="bg-slate-800 rounded-lg shadow-2xl p-8 border border-slate-700">
            <div className="mb-6">
              <h1 className="text-3xl font-bold text-white mb-2">Generated Prompt</h1>
              <a
                href={result.repoUrl}
                target="_blank"
                rel="noopener noreferrer"
                className="text-blue-400 hover:text-blue-300 text-sm"
              >
                Source: {result.repoName} →
              </a>
            </div>

            <div className="bg-slate-700 rounded-lg p-6 mb-6 border border-slate-600">
              <p className="text-slate-100 leading-relaxed whitespace-pre-wrap">
                {result.prompt}
              </p>
            </div>

            <div className="flex flex-col gap-3">
              <button
                onClick={() => {
                  navigator.clipboard.writeText(result.prompt);
                  alert("Prompt copied to clipboard!");
                }}
                className="w-full px-4 py-2 bg-green-600 hover:bg-green-700 text-white font-semibold rounded-lg transition-colors"
              >
                Copy Prompt
              </button>
              <div className="flex gap-3">
                <button
                  onClick={() => {
                    const text = `Check out this reverse-engineered prompt for ${result.repoName}:\n\n${result.prompt}\n\nGenerated by GitPrompt: ${window.location.href}`;
                    navigator.clipboard.writeText(text);
                    alert("Share text copied!");
                  }}
                  className="flex-1 px-4 py-2 bg-slate-600 hover:bg-slate-500 text-white font-semibold rounded-lg transition-colors"
                >
                  Copy Share Text
                </button>
                <button
                  onClick={() => {
                    const shareUrl = `https://twitter.com/intent/tweet?text=${encodeURIComponent(`Check out this reverse-engineered prompt for ${result.repoName}: ${window.location.href}`)}`;
                    window.open(shareUrl);
                  }}
                  className="flex-1 px-4 py-2 bg-blue-600 hover:bg-blue-700 text-white font-semibold rounded-lg transition-colors"
                >
                  Share on Twitter
                </button>
              </div>
            </div>
          </div>
        )}
      </div>
    </div>
  );
}
